# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd50841db83f5a03049899d96fdedf00002fa886c13907a8cbaefc2c7f9c28e75d08a640ce2a28553692dd92ca4452f8fcd778c9c8c2752c0e279df044c2cf80

test:
  secret_key_base: 7faa3a01893d350c29fbb49d996f01937d71c6bd9d17789b07c9dc6d6956b3a54473a566f607dafca52ae98a9c25393e008f1557a5ab94be155952584b0bd0cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
